[package]
name = "ejson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
view = { path = "../view" }
serde_json = "1.0.64"
regex = "1.5"